### PR TITLE
Add Israel

### PR DESCRIPTION
**Pull request by nirgn975**
Add new speakers from Israel.
Asked them on Twitter:
* [Uri Shaked](https://twitter.com/nirgn975/status/928174015746895876)
* [Nir kaufman](https://twitter.com/nirgn975/status/928173878760878080)

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hello ! 

Why is this WIP ? :)

**Comment by nirgn975** [comment]
@SaraVieira I asked couple of known Israeli speakers on Twitter and not all of them replay yet, I think it's batter to wait a day to do all of them at once then do a couple of separate PRs.
If they'll not replay until tomorrow I'll remove the WIP, resolve conflicts and it'll be ready for merge.

**Comment by nirgn975** [comment]
@SaraVieira @karlhorky Ready to review

**Review by karlhorky — APPROVED** [review]

**Comment by karlhorky** [comment]
Thanks!

**Pull request merged**
