### PR TITLE
Add Mike and Adam

### PR DESCRIPTION
**Pull request by adammenges**
Trying out instagram links, some are far more active there then twitter, hopefully that works for you too

### CODE REVIEW

**Comment by karlhorky** [comment]
Thanks for the contribution! The links are for contacting the person however, so let's keep it to something that is more of a messaging platform.

Another thing, what is "HI"? Maybe the non-abbreviation would be clearer?

**Comment by karlhorky** [comment]
> The links are for contacting the person however, so let's keep it to something that is more of a messaging platform.

That being said, if it's important to showcase the speaker's abilities I'd accept Instagram as a second link on the same line (with a space in between or something).

**Comment by karlhorky** [comment]
Hey @adammenges, I'm going to close this for now until you have time to look at this.

**Comment by adammenges** [comment]
Apologies, got busy with work. Reopening with feedback.

**Comment by karlhorky** [comment]
No problem, got it in now!

**Pull request closed without merging**
