### PR TITLE
added serena fritsch

### PR DESCRIPTION
**Pull request by kmossco**
Added another amazing speaker from Intercom. 🙌

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hello !

Can you please just let her know you are adding her ? 🙏

**Comment by kmossco** [comment]
@SaraVieira she knows and even chose the picture. 😉

**Review by karlhorky — APPROVED** [review]

**Comment by karlhorky** [comment]
Thanks!

**Comment by SaraVieira** [comment]
Oh awesome ! Thank you @kmossco

**Pull request merged**
