### PR TITLE
Add more awesome speakers

### PR DESCRIPTION
**Pull request by huijing**

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hello @huijing ,

Do you mind tweeting at them to make sure these people are okay with being added here ?

**Comment by huijing** [comment]
Hey @SaraVieira,
I've tweeted at them and here's to track the replies. The list is as follows (just FYI):
- Aysha Anggraini (yes)
- Zell Liew (yes)
- Rachel Andrew (yes)
- Vitaly Friedman (yes)
- Andrew Betts (yes)
- Heydon Pickering (yes)
- Jen Simmons (pending)
- Evangelina Ferreira (yes)
- Sara Soueidan (yes)
- Ally Long (yes)

**Comment by SaraVieira** [comment]
Thank you so much for letting them know !

Soooo, we have conflicts now 😭

**Comment by huijing** [comment]
No worries, resolved them.

**Review by karlhorky — APPROVED** [review]

**Comment by karlhorky** [comment]
Thanks very much @huijing ! Merging!

**Pull request merged**
