### PR TITLE
Add Jafar Husain

### PR DESCRIPTION
**Pull request by asyncanup**

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hello @asyncanup ,

Something weird seems to have happened here where you moved another spoeaker 

Can you please take a look at that ?

**Comment by karlhorky** [comment]
Uh, this is a bit off, can you fix that? Also, may be good to rebase on master to fix the conflicts. We have country headings now and it causes conflicts with this PR.


screen shot 2017-11-07 at 11 52 58


screen shot 2017-11-07 at 11 53 07

**Comment by karlhorky** [comment]
May be best just to open a new branch / PR for that.

**Comment by asyncanup** [comment]
@karlhorky how does it look now?

**Comment by SaraVieira** [comment]
Anjana Vakil stioll appears moved 😞

**Comment by asyncanup** [comment]
@SaraVieira ah, i actually did that to make it alphabetical, because every other name in that list was already alphabetical. want me to undo that change?

**Comment by SaraVieira** [comment]
Oh ! No you doing god's work then ! 😀

**Review by SaraVieira — APPROVED** [review]

**Comment by karlhorky** [comment]
Awesome, thanks guys.

**Pull request merged**
