### PR TITLE
Image fixes and new entries

### PR DESCRIPTION
**Pull request by MarcMunhoz**
Hey guys, how are you doing?

I added two amazing people and fixed some image links.

Later.

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hello!

Thank you so much for helping out! 😀
Did you let the people being added know?

**Comment by MarcMunhoz** [comment]
Hi @SaraVieira ! Yes, I sent them a message. Paul Irish responded positively, Peter not yet.

**Comment by SaraVieira** [comment]
Mind waiting for peter to respond ? :)

**Comment by MarcMunhoz** [comment]
Maybe he doesn't respond. You famous people are so busy... :smile:

**Comment by karlhorky** [comment]
@hiMunhoz can you publicly tweet Peter and copy the link here? Then we can merge.

**Comment by MarcMunhoz** [comment]
Sure... [Tweet here](https://twitter.com/heyMunhoz/status/935553869316313088)

**Comment by karlhorky** [comment]
Thanks, merging.

**Pull request merged**
