### PR TITLE
Organized by country

### PR DESCRIPTION
**Pull request by erikras**
- Created table of contents
- Added emoji flags

Closes #18.

### CODE REVIEW

**Comment by SaraVieira** [comment]
This looks dope !

The line breaks are pretty broken though :(

screen shot 2017-11-06 at 16 51 06

**Comment by erikras** [comment]
Yeah, not sure how that happened. 😦

**Comment by SaraVieira** [comment]
This repo has thought me that markdown is so much more tricky then it appears to be !

**Comment by erikras** [comment]
I mean, _tables_ would solve it, but 🤮!

**Comment by erikras** [comment]
Okay, so I think this might be a problem with the Github preview only. If you copy all the markdown and paste it into, say, an issue or PR, you get something like this:

---

# Australia 🇦🇺

### Melbourne



Glen Maddern
Topics: CSS, Styled Components, React, JavaScript
https://twitter.com/glenmaddern



Karolina Szczur
Topics: CSS, HTML, Web, Inclusivity, Diversity
https://twitter.com/fox

---

So I _think_ this can be merged safely. 🤞

**Comment by erikras** [comment]
@karlhorky You should merge asap before too many other PRs build up.

**Comment by SaraVieira** [comment]
@karlhorky can we merge this?

**Comment by karlhorky** [comment]
> I think this might be a problem with the Github preview only

Nope, the significant whitespace at the end of the lines was stripped. We'll need to fix before merging.

screen shot 2017-11-07 at 09 13 30

I removed the table of contents for now as well, because I don't want to maintain it if possible.

**Comment by karlhorky** [comment]
Really cool PR though! Look forward to getting this in!

**Comment by karlhorky** [comment]
So what I may end up doing is copying out the countries and just opening a new PR, so that there's a minimal set of changes with the latest stuff.

**Comment by karlhorky** [comment]
Ah looks like Zurich (and Sebastian) was lost in the shuffle here too. Adding him back.

**Comment by karlhorky** [comment]
Ok, done. Would appreciate if you guys could take a look a the new PR #53

**Pull request closed without merging**
