### PR TITLE
Add Speakers

### PR DESCRIPTION
**Pull request by matuzo**
I've added Job, Scott, Hala, Eric, Doug, Carie, Jesse, Cordelia, Jenn, Shell, Adrian and I've let them know that they're on the list here:

<https://twitter.com/mmatuzo/status/1052992249737371649>

### CODE REVIEW

**Comment by svinkle** [comment]
Thanks, @matuzo! ☺️

**Comment by matuzo** [comment]
🙌On 18 Oct 2018 15:01, Scott Vinkle <notifications@github.com> wrote:Thanks, @matuzo! ☺️

**Comment by SaraVieira** [comment]
Thank you so much for helping this community grow @matuzo 😃

**Comment by matuzo** [comment]
> Thank you so much for helping this community grow @matuzo 😃

No, thank you :)

**Pull request merged**
