### PR TITLE
Added Codebeast and Unicodeveloper

### PR DESCRIPTION
**Pull request by yemiwebby**
I've added Christian Nwamba (Codebeast) and Otemuyiwa Prosper (Unicodeveloper) I've let them know that they are on the list here:

<https://twitter.com/yemiwebby/status/929377472658984960>
<https://twitter.com/yemiwebby/status/929384631803228160>

### CODE REVIEW

**Comment by yemiwebby** [comment]
Added a new awesome speaker

**Comment by SaraVieira** [comment]
Hello !

Awesome ! Can you please just remove the duplicated headers for lagos ?

**Comment by yemiwebby** [comment]
Done!!

**Comment by SaraVieira** [comment]
Merged ! Thank you :)

**Pull request merged**
