### PR TITLE
Add links to bahmutov's slides and videos

### PR DESCRIPTION
**Pull request by bahmutov**

### CODE REVIEW

**Comment by karlhorky** [comment]
Hm, looks like this removes some speakers. Want to add them back?

**Comment by karlhorky** [comment]
Maybe we should add a heading or bullet point or both to demarcate this visually a bit.

**Comment by karlhorky** [comment]
I've tried this out in this branch, what do you think?

screen shot 2017-11-06 at 17 23 16

**Comment by karlhorky** [comment]
If it looks good just add back the removed speakers and this one looks good to go.

**Comment by bahmutov** [comment]
this is so weird why some speakers were removed.

**Comment by bahmutov** [comment]
made separate clean pull request

**Comment by karlhorky** [comment]
Thanks, merged!

**Pull request closed without merging**
