### PR TITLE
Guinness Goodness :) 🍻

### PR DESCRIPTION
**Pull request by lmammino**
I've added several great speakers from Ireland and I've let them know that they're on the list here:

- https://twitter.com/loige/status/930127843094335494
- https://twitter.com/loige/status/930127931099287553
- https://twitter.com/loige/status/930127983276449797
- https://twitter.com/loige/status/930128040369246208
- https://twitter.com/loige/status/930128085646749696
- https://twitter.com/loige/status/930128147672166400
- https://twitter.com/loige/status/930128384302174210
- https://twitter.com/loige/status/930128411233783808
- https://twitter.com/loige/status/930128458436562944
- https://twitter.com/loige/status/930128513461555203
- https://twitter.com/loige/status/930128559624073216
- https://twitter.com/loige/status/930128616607842304
- https://twitter.com/loige/status/930128663437246465
- https://twitter.com/loige/status/930128732853030913
- https://twitter.com/loige/status/930128776146640896
- https://twitter.com/loige/status/930128826092392448
- https://twitter.com/loige/status/930132347751673856
- https://twitter.com/loige/status/930135088876212224

### CODE REVIEW

**Comment by karlhorky** [comment]
Just some small edits then it's ready to go.

**Review by karlhorky — APPROVED** [review]

**Comment by lmammino** [comment]
Awesome, thanks

**Comment by lmammino** [comment]
Will you take care of the merge or do you expect me to do something else?

**Review by karlhorky — APPROVED** [review]

**Comment by karlhorky** [comment]
@lmammino just going to check all the links against the speakers in the PR and then I'll merge :) Thanks for all the work!

**Pull request merged**
