### PR TITLE
Add Bapusaheb Patil (@bapspatil)

### PR DESCRIPTION
**Pull request by bapspatil**
I've added Bapusaheb Patil (myself) and I've let them know that they're on the list here:

https://twitter.com/baps_patil/status/1073574181646692352
<br>
Slides, events and other information regarding all my talks can be found here: <b>https://bapspatil.com/talks<b>

### CODE REVIEW

**Comment by karlhorky** [comment]
Thanks! Just accepting one non-external link at the moment (Twitter). Can you update it?

**Comment by bapspatil** [comment]
Sure! Let me get right to that.

**Comment by bapspatil** [comment]
Done! :)

**Review by karlhorky — APPROVED** [review]

**Comment by karlhorky** [comment]
Thanks so much! Merged.

**Comment by bapspatil** [comment]
Thank you! 😄

**Pull request merged**
