### PR TITLE
add Alex Lobera

### PR DESCRIPTION
**Pull request by horacioh**

### CODE REVIEW

**Comment by SaraVieira** [comment]
Thank you 😀

Can you please just let him know that you are adding him ? :)

**Comment by horacioh** [comment]
sure!!

**Comment by horacioh** [comment]
Done! https://twitter.com/hhg2288/status/927646735803080704

**Comment by SaraVieira** [comment]
Thank You ! 😀

There were some weird conflicts here so I just added him in master and closes this one but It's added 🎉

**Pull request closed without merging**
