### PR TITLE
Add country headings

### PR DESCRIPTION
**Pull request by karlhorky**
Closes #18 
Closes #47 

Followup from these PRs above.

cc @SaraVieira @erikras

### CODE REVIEW

**Comment by karlhorky** [comment]
@erikras and @SaraVieira, please take a look! :) Let's get this one in!

**Comment by karlhorky** [comment]
Ok, I'm going to merge this so that I can continue on the rest of the PRs. Please take a look when you have a chance @erikras @SaraVieira and I can do any necessary changes in followup pull requests.

**Comment by karlhorky** [comment]
Thanks to @erikras for lots of work on it.

**Comment by kingthorin** [comment]
@erikras thanks for doing this!

**Pull request merged**
