### PR TITLE
Add (embarrassingly missing) alt text for images

### PR DESCRIPTION
**Pull request by didoo**
As Léonie Watson pointed out, all the  tags are missing the alt text (see https://github.com/karlhorky/awesome-speakers/pull/71#issuecomment-343608435). 
I have added it for all the speakers in the list and unified as much as possible the spaces.

please @SaraVieira @karlhorky can you pull this change as soon as possible to avoid too many conflicts?

### CODE REVIEW

**Comment by SaraVieira** [comment]
You are a hero!!!!

**Comment by SaraVieira** [comment]
Give m an hour and I will merge this!!!

**Comment by karlhorky** [comment]
Have some comments, wait on merging.

**Comment by didoo** [comment]
@SaraVieira I have checked and @karlhorky is right, now the indentation of the rendered Readme is messed up, let me fix it (sorry, but in the Atom Markdown previewer it was right)

**Comment by karlhorky** [comment]
Okay, so I think we should take Léonie's second suggestion (empty alt tag) because:

1. I don't think that it adds enough and I think it actually hurts screen reader usability to always have to skip through the headshot image.
2. If we want the alt tag to be accurate, the content will need to be custom based on the image. Not every image will be a headshot.
3. Because this is a non-visible change, this will get forgotten in probably most PRs. Often even the visual changes are not implemented correctly as it is.
4. It adds one more step to add a new speaker.
5. [It's ok if the image is described in the text already](https://twitter.com/Una/status/930863404499329027).

I'll make the changes to transition to an empty alt tag. Thanks for the PR!

**Comment by karlhorky** [comment]
> the indentation of the rendered Readme is messed up

Ah right, I didn't even see that yet. I'll open a new branch / PR for the changes then.

**Comment by didoo** [comment]
@karlhorky I have fixed the spacing, now it looks correct: https://github.com/didoo/awesome-speakers/tree/add-alt-text but I have noticed tat some are not correctly rendered, I'll fix them now.
do you prefer me to add fix them or you just close this PR and add an empty alt text to all the images in a separate PR?

**Comment by karlhorky** [comment]
I just merged #77 with the empty alt attributes. Thanks for your PRs!

**Pull request closed without merging**
