### PR TITLE
Emoji flags!! 😆

### PR DESCRIPTION
**Pull request by erikras**
Because everyone loves emoji!

### CODE REVIEW

**Comment by SaraVieira** [comment]
@erikras This is awesome ! 

But it did get behind the train , can you fix the issues ? Or maybe start over if its easier :(

**Comment by karlhorky** [comment]
Yeah, wasn't sure about maintaining this one. Still not sure.

If we decide to add countries as @kingthorin [proposed](https://github.com/karlhorky/awesome-speakers/pull/41#issuecomment-342151519) then maybe it makes sense.

It's all more overhead for adding new people though, not sure if the searchability is actually really an issue worth solving.

**Comment by erikras** [comment]
> Yeah, wasn't sure about maintaining this one. Still not sure.

It's not the end of the world if someone adds a new country and doesn't do the emoji flag. I think better with than without, but.... it's your doc.

**Comment by erikras** [comment]
It was quite a geography quiz doing these. I've resolved conflicts. Merge now if you're gonna.

No hard feelings if you don't, of course. 😄

**Comment by karlhorky** [comment]
Want to do a shot at it with the country headings? At least just 2 or 3 to see how it feels in the doc? I think with the country headings it makes more sense.

**Pull request closed without merging**
