### PR TITLE
Added more speakers from all around the world

### PR DESCRIPTION
**Pull request by didoo**
I have added the following amazing speakers from my "personal" list of favourite speakers:
- Mark Dalgleish
- Phil Nash
- Jeremy Keith
- Paul Robert Lloyd
- Vitaly Friedman
- Lu Yu
- Alessandro Cinelli 'Cirpo'
- Alexandra Deschamps-Sonsino
- Alla Kholmatova
- Bodil Stokke
- Caroline Jarrett
- Davide 'Folletto' Casali
- Jessica Rose
- Lily Dart
- Melinda Seckington
- Patrick Hamann
- Peter Gasston
- Seren Davies
- Diana Mounter
- Lara Hogan
- Lis Pardi
- Brad Frost
- Micah Godbolt
- Beth Dean
- Brynn Evans
- Jon Gold
- Stephanie Rewis

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hello @daliborgogic ,

So some harsh conflicts have appeared :(

Mind fixing that ? :(

**Comment by daliborgogic** [comment]
Hi @SaraVieira Conflicts are [fixed](https://github.com/karlhorky/awesome-speakers/pull/62).

**Comment by SaraVieira** [comment]
Merged in #62

**Comment by karlhorky** [comment]
Notified here:

https://twitter.com/karlhorky/status/928203727986675712
https://twitter.com/karlhorky/status/928203885981917186

**Pull request closed without merging**
