### PR TITLE
added Anjana Vakil to San Francisco

### PR DESCRIPTION
**Pull request by ferakpeter**

### CODE REVIEW

**Comment by SaraVieira** [comment]
Helllo @ferakpeter !

Thank you  so much , does she know whe is being added ? :)

**Comment by ferakpeter** [comment]
Not yet! I will tweet it.

**Comment by SaraVieira** [comment]
That would be awesome ! THank you :)

**Comment by karlhorky** [comment]
Thanks for tweeting! We'll make any changes if it's not cool with Anjana.

**Pull request merged**
