### PR TITLE
Added Lisa Huang to San Francisco section

### PR DESCRIPTION
**Pull request by lisaychuang**
Added myself to the list! Will you consider organizing the countries and speakers alphabetically (first or last name)?

### CODE REVIEW

**Comment by karlhorky** [comment]
Oh, this pull request strips some needed white space. I will add you in a new commit.

As for the ordering, yes, this is supposed to be ordered alphabetically. I will fix this too.

**Comment by karlhorky** [comment]
Added you / fixed ordering in 973e6c1

**Comment by lisaychuang** [comment]
Thanks for creating this repo!

**Comment by karlhorky** [comment]
No problem, thanks for contributing!

**Pull request closed without merging**
