### PR TITLE
Adding new speakers from Wroclaw

### PR DESCRIPTION
**Pull request by konradck**
I've added <person(s)> and I've let them know that they're on the list.

### CODE REVIEW

**Comment by karlhorky** [comment]
Hey Konrad, can you post your link to your tweet to these people? Or if you let them know personally, we can just merge.

**Comment by konradck** [comment]
Hi Karl! I told them personally, they're my colleagues :) but I can also do it on twitter

**Comment by karlhorky** [comment]
Oh, ok, no problem then. Merging :)

**Review by karlhorky — APPROVED** [review]
Thanks!

**Pull request merged**
